#!/bin/bash

envtype=${1}
DIR=${2:-$(pwd)}

SCRIPT=""
case "$(uname -s)" in
	Darwin*)    SCRIPT="$(greadlink -f "$0")";;
	*)          SCRIPT="$(readlink -f "$0")"
esac
SCRIPTDIR="$(dirname "$SCRIPT")"

echo $SCRIPTDIR

if [[ ! -z "$envtype" ]]; then
	envtype="-$envtype"
fi

docker run \
	--rm \
	-it \
	-v "$SCRIPTDIR/base/dotfiles/coc/package.json:/root/.config/coc/extensions/package.json" \
	-v "$SCRIPTDIR/base/dotfiles/nvim/init.vim:/root/.config/nvim/init.vim" \
	-v "$SCRIPTDIR/base/dotfiles/nvim/coc-settings.json:/root/.config/nvim/coc-settings.json" \
	-v "$SCRIPTDIR/base/dotfiles/zsh/.zshrc:/root/.zshrc" \
	-v "$DIR:/root/code" \
	timsmart/devenv$envtype:latest
