#!/bin/bash

envtype=${1}
DIR=${2:-$(pwd)}

SCRIPT=""
case "$(uname -s)" in
	Darwin*)    SCRIPT="$(greadlink -f "$0")";;
	*)          SCRIPT="$(readlink -f "$0")"
esac
SCRIPTDIR="$(dirname "$SCRIPT")"

if [[ ! -z "$envtype" ]]; then
	envtype="-$envtype"
fi

IMAGE=timsmart/devenv$envtype:latest
# docker pull $IMAGE

if ! docker ps | grep -q pinata-sshd; then
	bash "$SCRIPTDIR/tools/ssh-forward.sh"
fi

exec docker run \
	--rm \
	-it \
	-v ssh-agent:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent/ssh-agent.sock \
	-v "$SCRIPTDIR/base/dotfiles/coc/package.json:/root/.config/coc/extensions/package.json" \
	-v "$SCRIPTDIR/base/dotfiles/nvim/init.vim:/root/.config/nvim/init.vim" \
	-v "$SCRIPTDIR/base/dotfiles/nvim/coc-settings.json:/root/.config/nvim/coc-settings.json" \
	-v "$SCRIPTDIR/base/dotfiles/zsh/zshrc:/root/.zshrc" \
	-v "$DIR:/root/code" \
	$IMAGE
